version: '3'

services:

    artists:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: artists
        ports:
            - "3308:3306"
            
    customers:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: 123
            MYSQL_DATABASE: customers
        ports:
            - "3309:3306"
            
    admin:
        image: adminer
        ports:
            - 8080:8080